// Generated by tool/generate_google_route_enrichment.dart.
// Keep this file checked in so Google-derived stop expansions can be used
// without runtime API calls. When no Google data has been generated yet, the
// lists below stay empty and the app falls back to curated/manual stop data.

class GoogleImportedStopSpec {
  const GoogleImportedStopSpec({
    required this.id,
    required this.name,
    this.nameTelugu = '',
    required this.lat,
    required this.lng,
    this.placeId = '',
  });

  final String id;
  final String name;
  final String nameTelugu;
  final double lat;
  final double lng;
  final String placeId;
}

class GoogleImportedRouteSpec {
  const GoogleImportedRouteSpec({
    required this.routeId,
    required this.baseRoute,
    required this.from,
    required this.to,
    required this.stopIds,
    required this.majorStopIds,
  });

  final String routeId;
  final String baseRoute;
  final String from;
  final String to;
  final List<String> stopIds;
  final List<String> majorStopIds;
}

const List<GoogleImportedStopSpec> googleImportedStops = [];
const List<GoogleImportedRouteSpec> googleImportedRouteSpecs = [];
