import 'dart:io';

import 'package:vizag_bus_live/data/google_route_enrichment_data.dart';
import 'package:vizag_bus_live/data/vizag_data.dart';
import 'package:vizag_bus_live/services/google_route_enrichment_service.dart';

void main(List<String> args) async {
  final routesApiKey = _readApiKey(
    'GOOGLE_MAPS_ROUTES_API_KEY',
    'GOOGLE_MAPS_PLATFORM_API_KEY',
    'GOOGLE_MAPS_API_KEY',
  );
  final placesApiKey = _readApiKey(
    'GOOGLE_MAPS_PLACES_API_KEY',
    'GOOGLE_MAPS_PLATFORM_API_KEY',
    'GOOGLE_MAPS_API_KEY',
  );

  if (routesApiKey == null || placesApiKey == null) {
    stderr.writeln(
      'Missing Google Maps Platform keys. Set '
      'GOOGLE_MAPS_ROUTES_API_KEY and GOOGLE_MAPS_PLACES_API_KEY, or a shared '
      'GOOGLE_MAPS_PLATFORM_API_KEY.',
    );
    exitCode = 64;
    return;
  }

  final selectedRoutes = _selectRoutes(args);
  if (selectedRoutes.isEmpty) {
    stderr.writeln('No routes matched: ${args.join(', ')}');
    exitCode = 1;
    return;
  }

  final knownGeneratedStops = <String, BusStop>{
    for (final stop in googleImportedStops)
      stop.id: BusStop(
        id: stop.id,
        name: stop.name,
        nameTelugu: stop.nameTelugu,
        lat: stop.lat,
        lng: stop.lng,
      ),
  };
  final generatedRoutesById = <String, GoogleImportedRouteSpec>{
    for (final spec in googleImportedRouteSpecs) spec.routeId: spec,
  };
  final service = GoogleRouteEnrichmentService(
    routesApiKey: routesApiKey,
    placesApiKey: placesApiKey,
  );

  try {
    for (final route in selectedRoutes) {
      stdout
          .writeln('Enriching ${route.routeId} (${route.from} -> ${route.to})');
      final result = await service.enrichRoute(
        route,
        knownStopsById: knownGeneratedStops,
      );
      if (result == null) {
        stdout.writeln('  skipped: no stronger Google-enriched stop sequence');
        continue;
      }

      for (final stop in result.discoveredStops) {
        knownGeneratedStops[stop.id] = BusStop(
          id: stop.id,
          name: stop.name,
          nameTelugu: stop.nameTelugu,
          lat: stop.lat,
          lng: stop.lng,
        );
      }

      generatedRoutesById[result.routeId] = GoogleImportedRouteSpec(
        routeId: result.routeId,
        baseRoute: result.baseRoute,
        from: result.from,
        to: result.to,
        stopIds: result.stopIds,
        majorStopIds: result.majorStopIds,
      );
      stdout.writeln(
        '  ok: ${route.stopIds.length} -> ${result.stopIds.length} stops '
        '(${result.discoveredStops.length} Google-derived stops)',
      );
    }
  } finally {
    service.close();
  }

  final outputFile = File(
    '${Directory.current.path}${Platform.pathSeparator}lib'
    '${Platform.pathSeparator}data'
    '${Platform.pathSeparator}google_route_enrichment_data.dart',
  );
  outputFile.writeAsStringSync(
    _renderDartFile(
      stops: knownGeneratedStops.values.toList(growable: false)
        ..sort((a, b) => a.id.compareTo(b.id)),
      routes: generatedRoutesById.values.toList(growable: false)
        ..sort((a, b) => a.routeId.compareTo(b.routeId)),
    ),
  );

  stdout.writeln('');
  stdout.writeln(
    'Wrote ${generatedRoutesById.length} route specs and '
    '${knownGeneratedStops.length} Google stop specs to ${outputFile.path}',
  );
}

List<BusRoute> _selectRoutes(List<String> args) {
  if (args.isEmpty) {
    return [...VizagRoutes.all]..sort((a, b) => a.routeId.compareTo(b.routeId));
  }

  final seenRouteIds = <String>{};
  final matches = <BusRoute>[];
  for (final selector in args.map((value) => value.trim().toLowerCase())) {
    for (final route in VizagRoutes.all) {
      if (route.routeId.toLowerCase() != selector &&
          route.number.toLowerCase() != selector) {
        continue;
      }
      if (seenRouteIds.add(route.routeId)) {
        matches.add(route);
      }
    }
  }
  matches.sort((a, b) => a.routeId.compareTo(b.routeId));
  return matches;
}

String? _readApiKey(String primary, String secondary, String tertiary) {
  for (final key in [primary, secondary, tertiary]) {
    final value = Platform.environment[key]?.trim();
    if (value != null && value.isNotEmpty) {
      return value;
    }
  }
  return null;
}

String _renderDartFile({
  required List<BusStop> stops,
  required List<GoogleImportedRouteSpec> routes,
}) {
  final buffer = StringBuffer()
    ..writeln('// Generated by tool/generate_google_route_enrichment.dart.')
    ..writeln('// Do not edit by hand.')
    ..writeln('')
    ..writeln('class GoogleImportedStopSpec {')
    ..writeln('  const GoogleImportedStopSpec({')
    ..writeln('    required this.id,')
    ..writeln('    required this.name,')
    ..writeln("    this.nameTelugu = '',")
    ..writeln('    required this.lat,')
    ..writeln('    required this.lng,')
    ..writeln("    this.placeId = '',")
    ..writeln('  });')
    ..writeln('')
    ..writeln('  final String id;')
    ..writeln('  final String name;')
    ..writeln('  final String nameTelugu;')
    ..writeln('  final double lat;')
    ..writeln('  final double lng;')
    ..writeln('  final String placeId;')
    ..writeln('}')
    ..writeln('')
    ..writeln('class GoogleImportedRouteSpec {')
    ..writeln('  const GoogleImportedRouteSpec({')
    ..writeln('    required this.routeId,')
    ..writeln('    required this.baseRoute,')
    ..writeln('    required this.from,')
    ..writeln('    required this.to,')
    ..writeln('    required this.stopIds,')
    ..writeln('    required this.majorStopIds,')
    ..writeln('  });')
    ..writeln('')
    ..writeln('  final String routeId;')
    ..writeln('  final String baseRoute;')
    ..writeln('  final String from;')
    ..writeln('  final String to;')
    ..writeln('  final List<String> stopIds;')
    ..writeln('  final List<String> majorStopIds;')
    ..writeln('}')
    ..writeln('')
    ..writeln('const List<GoogleImportedStopSpec> googleImportedStops = [');

  for (final stop in stops) {
    buffer
      ..writeln('  GoogleImportedStopSpec(')
      ..writeln("    id: '${_escape(stop.id)}',")
      ..writeln("    name: '${_escape(stop.name)}',")
      ..writeln("    nameTelugu: '${_escape(stop.nameTelugu)}',")
      ..writeln('    lat: ${stop.lat.toStringAsFixed(7)},')
      ..writeln('    lng: ${stop.lng.toStringAsFixed(7)},')
      ..writeln('  ),');
  }

  buffer
    ..writeln('];')
    ..writeln('')
    ..writeln(
      'const List<GoogleImportedRouteSpec> googleImportedRouteSpecs = [',
    );

  for (final route in routes) {
    buffer
      ..writeln('  GoogleImportedRouteSpec(')
      ..writeln("    routeId: '${_escape(route.routeId)}',")
      ..writeln("    baseRoute: '${_escape(route.baseRoute)}',")
      ..writeln("    from: '${_escape(route.from)}',")
      ..writeln("    to: '${_escape(route.to)}',")
      ..writeln(
        '    stopIds: const [${route.stopIds.map((id) => "'${_escape(id)}'").join(', ')}],',
      )
      ..writeln(
        '    majorStopIds: const [${route.majorStopIds.map((id) => "'${_escape(id)}'").join(', ')}],',
      )
      ..writeln('  ),');
  }

  buffer.writeln('];');
  return buffer.toString();
}

String _escape(String value) =>
    value.replaceAll('\\', '\\\\').replaceAll("'", "\\'");
