import 'dart:io';

import 'package:vizag_bus_live/data/vizag_data.dart';

void main() {
  final outputFile = File(
    '${Directory.current.path}${Platform.pathSeparator}lib'
    '${Platform.pathSeparator}data'
    '${Platform.pathSeparator}manual_route_enrichment_data.dart',
  );

  final routes = [...VizagRoutes.all]
    ..sort((a, b) => a.routeId.compareTo(b.routeId));

  outputFile.writeAsStringSync(_renderManualRouteFile(routes));
  stdout.writeln(
    'Wrote ${routes.length} manual route override templates to '
    '${outputFile.path}',
  );
}

String _renderManualRouteFile(List<BusRoute> routes) {
  final buffer = StringBuffer()
    ..writeln('// Generated by tool/generate_manual_route_enrichment.dart.')
    ..writeln('// Edit this file manually to add missing sub-stops, junctions,')
    ..writeln('// and exact coordinates. Add every new stop once in')
    ..writeln(
        '// manualStopOverrides, then reuse its id inside the route stopIds.')
    ..writeln('')
    ..writeln('class ManualStopOverrideSpec {')
    ..writeln('  const ManualStopOverrideSpec({')
    ..writeln('    required this.id,')
    ..writeln('    required this.name,')
    ..writeln("    this.nameTelugu = '',")
    ..writeln('    required this.lat,')
    ..writeln('    required this.lng,')
    ..writeln('  });')
    ..writeln('')
    ..writeln('  final String id;')
    ..writeln('  final String name;')
    ..writeln('  final String nameTelugu;')
    ..writeln('  final double lat;')
    ..writeln('  final double lng;')
    ..writeln('}')
    ..writeln('')
    ..writeln('class ManualRouteOverrideSpec {')
    ..writeln('  const ManualRouteOverrideSpec({')
    ..writeln('    required this.routeId,')
    ..writeln('    required this.baseRoute,')
    ..writeln('    required this.from,')
    ..writeln('    required this.to,')
    ..writeln('    required this.stopIds,')
    ..writeln('    required this.majorStopIds,')
    ..writeln('  });')
    ..writeln('')
    ..writeln('  final String routeId;')
    ..writeln('  final String baseRoute;')
    ..writeln('  final String from;')
    ..writeln('  final String to;')
    ..writeln('  final List<String> stopIds;')
    ..writeln('  final List<String> majorStopIds;')
    ..writeln('}')
    ..writeln('')
    ..writeln('const List<ManualStopOverrideSpec> manualStopOverrides = [')
    ..writeln('  // Example:')
    ..writeln("  // ManualStopOverrideSpec(")
    ..writeln("  //   id: 'new_junction',")
    ..writeln("  //   name: 'New Junction',")
    ..writeln("  //   lat: 17.0000000,")
    ..writeln("  //   lng: 83.0000000,")
    ..writeln('  // ),')
    ..writeln('];')
    ..writeln('')
    ..writeln('const List<ManualRouteOverrideSpec> manualRouteOverrides = [');

  for (final route in routes) {
    buffer
      ..writeln(
          "  // ${_escape(route.routeId)}: ${_escape(route.from)} -> ${_escape(route.to)}")
      ..writeln('  ManualRouteOverrideSpec(')
      ..writeln("    routeId: '${_escape(route.routeId)}',")
      ..writeln("    baseRoute: '${_escape(route.number)}',")
      ..writeln("    from: '${_escape(route.from)}',")
      ..writeln("    to: '${_escape(route.to)}',")
      ..writeln(
        '    stopIds: [${route.stopIds.map((id) => "'${_escape(id)}'").join(', ')}],',
      )
      ..writeln(
        '    majorStopIds: [${route.visibleStopIds.map((id) => "'${_escape(id)}'").join(', ')}],',
      )
      ..writeln('  ),')
      ..writeln('');
  }

  buffer.writeln('];');
  return buffer.toString();
}

String _escape(String value) =>
    value.replaceAll('\\', '\\\\').replaceAll("'", "\\'");
